version: '2'
services:

  django:
    env_file:
      - .env.prod
    environment:
       - DEBUG=False
       - LETSENCRYPT_HOST=${VIRTUAL_HOST_WEB}
       - VIRTUAL_HOST=${VIRTUAL_HOST_WEB}
       - CACHE_LOCATION=memcached:11211
       - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
       - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    depends_on:
       - memcached
    expose:
      - "8000"
    volumes:
      - ./staticfiles:/code/staticfiles
    command: ["gunicorn", "jarbas.wsgi:application", "--reload", "--bind", "0.0.0.0:8000", "--workers", "4"]

  tasks:
    env_file:
      - .env.prod
    environment:
       - DEBUG=False
       - CACHE_LOCATION=memcached:11211
       - CACHE_BACKEND=django.core.cache.backends.memcached.MemcachedCache
       - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    depends_on:
       - memcached

  elm:
    command: ["npm", "run", "assets"]
    volumes:
      - ./staticfiles:/code/jarbas/frontend/static

  postgres:
    expose:
      - "5432"

  memcached:
    image: memcached:1.5.1-alpine

  nginx:
    image: datasciencebr/jarbas-server
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/code/staticfiles
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "/etc/nginx/certs"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx"
